const app=document.querySelector('#demo'),note=document.querySelector('#notice');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pretty=v=>JSON.stringify(v,null,2);
const sources=['src/events.ts','src/planner.ts','src/journal.ts','src/adapters.ts','src/auth.ts','src/worker.ts','test/bridge.test.ts','test/wire-payload.test.ts','test/browser-demo.test.ts'];
const chapters=['Link','Reply','Mirror','Protect','Recover','Resolve'];
let worker,serial=0,state,stage=0,started=false,busy=false,progress=0,tab='conversation',timer,replyText='I reproduced the issue. The fix is ready for review.',slackText='Thanks. I can test the fix this afternoon.',sourceText='',sourceFile='',epoch=0;
const pending=new Map();
function startWorker(){worker=new Worker(new URL('./worker.js',import.meta.url),{type:'module'});worker.onmessage=({data})=>{const p=pending.get(data.id);if(!p)return;clearTimeout(p.timer);pending.delete(data.id);data.error?p.reject(Error(data.error)):p.resolve(data.result);};worker.onerror=()=>{for(const p of pending.values()){clearTimeout(p.timer);p.reject(Error('The browser journal could not start. Reload and try again.'));}pending.clear();};}
function call(action,value=''){return new Promise((resolve,reject)=>{const id=++serial;const timer=setTimeout(()=>{worker.terminate();for(const p of pending.values()){clearTimeout(p.timer);p.reject(Error('The browser engine timed out. Start the walkthrough again.'));}pending.clear();started=false;startWorker();render();},20000);pending.set(id,{resolve,reject,timer});worker.postMessage({id,action,value});});}
startWorker();
function announce(text){note.textContent=text;note.className='visible';clearTimeout(timer);timer=setTimeout(()=>note.className='',8000);}
function banner(){return '<div class="demo-banner"><span></span><strong>Browser walkthrough</strong><p>The real event parser, planner and journal run locally. Slack and Jira are simulated. No accounts required.</p></div>';}
function landing(){return `<section class="hero"><div><p class="eyebrow">SLACK ↔ JIRA / WITHOUT THE MANUAL HANDOFF</p><h1>One conversation.<br>Two tools.</h1><p class="lead">Support stays in Slack.<br>Engineering stays in Jira.</p><p>A request becomes a ticket. Replies travel both ways. When delivery gets messy, the bridge shows exactly what needs attention.</p><div class="hero-actions"><button class="primary" data-action="start">Follow a request →</button><a href="#engineering">Take the technical route ↗</a></div><p class="caption">About 3 minutes · No signup · Everything stays in this tab</p></div><aside class="hero-conversation"><div class="mini-heading"><span># support</span><small>SLACK</small></div><p class="mini-user">Maya <small>10:00</small></p><p class="mini-message">The weekly report export fails when I select a date range. Can someone take a look?</p><div class="bridge-rule"><span>↓</span><p>Thread linked to <strong>OPS-1</strong></p></div><div class="mini-ticket"><span>JIRA / OPS-1</span><h3>Report export fails</h3><p>Open → In progress → Done</p></div><div class="hero-caption">A synthetic example. The walkthrough creates the link using the real journal.</div></aside></section><section class="three-parts"><article><span>01</span><h3>Keep the context</h3><p>Thread and ticket identities stay linked, so replies reach the right conversation.</p></article><article><span>02</span><h3>Stop the loops</h3><p>Repeated events and bridge-authored echoes are recognized before another write.</p></article><article><span>03</span><h3>Recover with evidence</h3><p>A lost receipt becomes an uncertain hold. Inspect the destination before continuing.</p></article></section>`;}
function nav(){return `<nav class="stages" aria-label="Walkthrough stages">${chapters.map((name,i)=>`<button data-stage="${i}" ${i>progress?'disabled':''} ${stage===i?'aria-current="step"':''}><span>${i+1}</span>${name}</button>`).join('')}</nav>`;}
function guidance(){
  const held=state?.effects.find(e=>e.status==='uncertain');
  const guides=[
    ['Send the request from Slack.','A native message event enters the bridge. The journal records the event before a Jira create request is delivered. The ticket receipt establishes the identity link.',`<button class="primary" data-action="root" ${state?.links.length?'disabled':''}>${state?.links.length?'Thread & ticket linked ✓':'Create the linked ticket →'}</button>`],
    ['Reply where engineering already works.','A Jira comment is converted from rich text and mirrored into the original Slack thread. The reply keeps its context, rather than becoming a new channel message.',`<label for="jira-reply">Jira comment</label><textarea id="jira-reply">${esc(replyText)}</textarea><button class="primary" data-action="reply">Send the Jira reply →</button>`],
    ['Let the requester respond in Slack.','The return message becomes a comment on the same Jira ticket. Nobody has to copy the thread into a second tool.',`<label for="slack-reply">Slack reply</label><textarea id="slack-reply">${esc(slackText)}</textarea><button class="primary" data-action="slack-reply">Mirror the Slack reply →</button>`],
    ['What if the same event arrives twice?','Webhook systems retry. Replay the last event, then send a bridge-authored echo. Neither should create another destination write.',`<button class="primary" data-action="duplicate">Replay the last event</button><button data-action="echo">Send a bot echo</button><p class="caption">Inspect the journal to see duplicate detection and the ignored echo.</p>`],
    ['The write happened. The receipt did not arrive.','A timeout does not tell you whether Slack received the message. This case deliberately applies the simulated write, loses its receipt, and holds the delivery. Reconcile against the mock destination receipt to continue.',`<button class="primary" data-action="lost" ${held?'disabled':''}>Simulate a lost receipt</button>${held?'<button data-action="reconcile">Verify receipt & reconcile →</button><button data-action="restart">Reconstruct the journal</button>':''}<p class="caption">Journal reconstruction keeps the same in-memory SQLite database. It does not emulate a Cloudflare process restart.</p>`],
    ['Close it in Jira. Keep Slack informed.','Jira owns the status. A confirmed Done event updates the link and sends a final status message to Slack. Stale notifications are suppressed by the production planner.',`<button class="primary" data-action="status" ${held?'disabled':''}>Mark the Jira ticket Done →</button>${held?'<p class="caption">Reconcile the uncertain delivery first.</p>':''}<a class="text-link" href="#engineering">Explore the implementation ↗</a>`],
  ];
  const [title,description,controls]=guides[stage];
  return `<aside class="guide"><p class="eyebrow">${String(stage+1).padStart(2,'0')} / ${chapters[stage].toUpperCase()}</p><h2>${title}</h2><p>${description}</p><div class="guide-controls">${controls}</div><div class="guide-next"><button data-stage="${Math.max(0,stage-1)}" ${stage===0?'disabled':''}>← Back</button><button data-stage="${Math.min(5,stage+1)}" ${stage>=progress||stage===5?'disabled':''}>Next →</button></div></aside>`;
}
function conversation(){
  const receipts=state.receipts.slice().reverse(),link=state.links[0];
  const incoming=state.events.filter(e=>e.payload.kind==='root'||e.payload.kind==='reply').slice().reverse();
  const bubble=(name,body,mirrored=false)=>`<article class="message ${mirrored?'mirrored':''}"><span class="avatar">${esc(name[0])}</span><div><strong>${esc(name)}${mirrored?'<small>via Threadbridge</small>':''}</strong><p>${esc(body)}</p></div></article>`;
  const messages=(native,mirrored)=>[...native.map(e=>({created:e.created,name:e.payload.origin==='slack'?'Maya':'Sam',body:e.payload.text})),...mirrored.map(r=>({created:r.created,name:'Bridge',body:r.kind==='slack.post'?JSON.parse(r.request.body).text:readAdf(JSON.parse(r.request.body).body),mirrored:true}))].sort((a,b)=>a.created-b.created).map(m=>bubble(m.name,m.body,m.mirrored)).join('');
  const slack=messages(incoming.filter(e=>e.payload.origin==='slack'),receipts.filter(r=>r.kind==='slack.post'));
  const jira=messages(incoming.filter(e=>e.payload.origin==='ticket'&&e.payload.kind==='reply'),receipts.filter(r=>r.kind==='ticket.comment'));
  return `<div class="conversation-columns"><section class="slack-panel"><div class="conversation-heading"><span class="app-icon slack">#</span><div><h3>support</h3><small>Slack thread</small></div><span class="live-label">SIMULATED</span></div>${slack||'<div class="empty">Send the first request to start the thread.</div>'}</section><section class="jira-panel"><div class="conversation-heading"><span class="app-icon jira">◈</span><div><h3>${esc(link?.issue||'No ticket yet')}</h3><small>Jira issue</small></div><span class="live-label">SIMULATED</span></div>${link?`<div class="ticket-title"><span class="status">${esc(link.status)}</span><h3>Report export fails</h3><p>${esc(incoming.find(e=>e.payload.kind==='root')?.payload.text)}</p></div>${jira}`:'<div class="empty">The create receipt will establish the ticket link.</div>'}</section></div>`;
}
function readAdf(value){return typeof value==='string'?value:(value?.text||'')+(value?.content||[]).map(readAdf).join('');}
function evidence(){return `<section class="journal"><div class="journal-title"><h3>Event journal</h3><span>${state.events.length} events · ${state.receipts.length} simulated writes</span></div>${state.events.map(e=>`<div class="journal-row"><span class="event-origin">${e.payload.origin==='slack'?'Slack':'Jira'}</span><div><strong>${esc(e.id)}</strong><p>${esc(e.error||e.payload.text||e.payload.kind)}</p></div><span class="status ${esc(e.status)}">${esc(e.status)}</span></div>`).join('')||'<p class="empty">No events have been recorded.</p>'}<h3 class="effects-title">Delivery effects</h3>${state.effects.map(e=>`<div class="journal-row"><code>${esc(e.kind)}</code><div><strong>${esc(e.key)}</strong><p>${esc(e.error||e.receipt?.id||'Awaiting delivery')}</p></div><span class="status ${esc(e.status)}">${esc(e.status)}</span></div>`).join('')}</section>`;}
function requests(){return `<section class="requests"><p class="caption">Constructed by the real adapters. Responses and destination writes are simulated.</p>${state.receipts.map(r=>`<details><summary><strong>${esc(r.request.method)}</strong> ${esc(r.kind)} · ${esc(r.receipt.id)}</summary><pre>${esc(pretty(r.request))}</pre><h3>Simulated destination receipt</h3><pre>${esc(pretty(r.receipt))}</pre></details>`).join('')||'<p class="empty">No requests yet.</p>'}${state.wire?`<details><summary>Latest native input payload</summary><pre>${esc(pretty(state.wire))}</pre></details>`:''}</section>`;}
function workbench(){return `<section class="walkthrough">${nav()}<div class="workspace-head"><div><p class="eyebrow">A REQUEST, END TO END</p><h1>The conversation is the workflow.</h1></div><button data-action="reset">Start over ↻</button></div><div class="identity-bar"><span># support <b>↔</b> ${esc(state.links[0]?.issue||'Awaiting ticket')}</span><span>${state.links[0]?'Identity linked':'Not linked'} · ${state.effects.filter(e=>e.status==='uncertain').length} uncertain deliveries</span></div><div class="workbench"><section class="workspace"><div class="workspace-tabs" role="tablist" aria-label="Inspection view">${[['conversation','Conversation'],['journal','Journal'],['requests','Requests & payloads']].map(([id,label])=>`<button role="tab" aria-selected="${tab===id}" data-tab="${id}">${label}</button>`).join('')}</div><div class="workspace-body">${tab==='conversation'?conversation():tab==='journal'?evidence():requests()}</div>${state.result?`<div class="result-note">${state.result.duplicate?'Duplicate event recognized. No new destination write.':state.result.reconciled?'Receipt reconciled. The applied write was not repeated.':state.result.restarted?'Journal reconstructed. Existing links and uncertain holds retained.':'Event accepted by the journal.'}</div>`:''}</section>${guidance()}</div></section>`;}
function technical(){return `<section class="technical"><p class="eyebrow">ENGINEERING / THREADBRIDGE</p><h1>A durable handoff,<br>not a pair of webhooks.</h1><p class="lead">Identity, order and recovery matter as much as the happy path.</p><div class="architecture"><span>Signed ingress</span><b>→</b><span>Inbox</span><b>→</b><span>Event planner</span><b>→</b><span>Ordered outbox</span><b>→</b><span>Provider receipt</span></div><article><h2>The browser runs the real journal.</h2><p>The walkthrough bundles the production event parsers, canonical planner, SQL journal and mock adapter. SQLite runs as WebAssembly in a Web Worker. Accepted events, identity links, effects and receipts are real rows in this tab’s database.</p><p>Reloading the tab clears the database. Cloudflare’s persistent Durable Object storage, alarms and signed HTTP ingress are exercised by separate local Worker tests, not by this browser demo.</p></article><article><h2>A timeout is an uncertainty state.</h2><p>The adapter can apply a simulated write and then lose the receipt. The journal marks that effect uncertain, holds related delivery order, and requires a matching receipt to finish it. Reconstructing the journal preserves the hold without sending again.</p><p>This prevents blind retries. It does not guarantee exactly-once behavior for third-party APIs.</p></article><article><h2>The bridge knows its own echoes.</h2><p>Slack bot metadata and Jira bridge-origin properties stop mirrored events from becoming new writes. Event IDs are bound to payload fingerprints, so a conflicting retry cannot silently change an earlier accepted event.</p><p>Jira owns status. Older revisions and unsupported or restricted comments are suppressed by the canonical event planner and parsers.</p></article><article><h2>Ready to connect a sandbox?</h2><p>The repository includes a Cloudflare Worker, SQLite-backed Durable Object, Docker development setup, Mermaid architecture diagrams and native-payload tests. Slack/Jira permissions and live API parity still need a real sandbox account check.</p><a class="text-link" href="https://github.com/zulfkicar/threadbridge" target="_blank" rel="noopener noreferrer">Open the repository →</a></article><section class="source-list"><h2>Read the implementation</h2>${sources.map(f=>`<a href="#source/${f}">${esc(f)} ↗</a>`).join('')}</section><a class="text-link" href="#walkthrough">← Return to the walkthrough</a></section>`;}
function codeView(){const name=location.hash.slice(8);if(!sources.includes(name))return '<h1>Source file not found.</h1>';if(sourceFile!==name){sourceFile=name;sourceText='Loading source…';fetch('./source/'+name.replaceAll('/','-')+'.txt').then(async r=>{if(!r.ok)throw Error('Source snapshot unavailable');return r.text();}).then(text=>{if(sourceFile===name){sourceText=text;render();}}).catch(error=>{sourceText=error.message;render();});}return `<section class="technical"><p class="eyebrow">SOURCE DEEP DIVE</p><h1>${esc(name)}</h1><a class="text-link" href="#engineering">← Engineering notes</a><pre class="source-code">${esc(sourceText)}</pre></section>`;}
function render(){app.innerHTML=banner()+(location.hash.startsWith('#source/')?codeView():location.hash==='#engineering'?technical():started&&state?workbench():landing());if(busy)for(const button of app.querySelectorAll('button[data-action]'))button.disabled=true;}
async function start(){const generation=++epoch;busy=true;render();try{const next=await call('snapshot');if(generation!==epoch)return;state=next;started=true;stage=progress=0;location.hash='walkthrough';}finally{busy=false;render();}window.scrollTo(0,0);}
app.addEventListener('click',async e=>{const button=e.target.closest('button');if(!button||button.disabled)return;note.className='';try{
  if(button.dataset.stage){stage=Number(button.dataset.stage);render();window.scrollTo(0,0);return;}
  if(button.dataset.tab){tab=button.dataset.tab;render();return;}
  const action=button.dataset.action;if(action==='start')return await start();
  if(action==='reset'){worker.terminate();for(const p of pending.values()){clearTimeout(p.timer);p.reject(Error('Walkthrough reset'));}pending.clear();startWorker();state=null;started=false;return await start();}
  if(action){busy=true;render();try{state=await call(action,action==='reply'?replyText:action==='slack-reply'?slackText:'');if(['root','reply','slack-reply'].includes(action))progress=Math.max(progress,stage+1);if(action==='duplicate'||action==='echo')progress=Math.max(progress,4);if(action==='reconcile')progress=Math.max(progress,5);if(action==='lost'||action==='reconcile'||action==='restart'||action==='echo'||action==='duplicate')tab='journal';}finally{busy=false;render();}}
}catch(error){busy=false;render();announce(error.message);}});
app.addEventListener('input',e=>{if(e.target.id==='jira-reply')replyText=e.target.value;if(e.target.id==='slack-reply')slackText=e.target.value;});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});render();
