const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function diagramHtml(diagram,number,inline,notes,source){
 const parts=Object.entries(notes),id=diagram.file;
 return `<figure class="explorer" id="diagram-${id}" data-explorer>
 <div class="figure-heading"><div><span>SYSTEM MAP / ${String(number).padStart(2,'0')}</span><h3>${e(diagram.title)}</h3></div><span class="component-count">${parts.length} components</span></div>
 <div class="diagram-toolbar" hidden><div class="zoom-controls"><button type="button" data-action="out" aria-label="Zoom out">−</button><output data-zoom aria-label="Zoom level">100%</output><button type="button" data-action="in" aria-label="Zoom in">+</button><button type="button" data-action="fit">Fit</button><button type="button" data-action="actual">100%</button></div><button type="button" data-action="fullscreen" aria-label="Expand diagram">Expand ↗</button></div>
 <div class="explorer-body"><div class="canvas-wrap"><div class="diagram-canvas" id="${id}-view" tabindex="0" role="region" aria-label="${e(diagram.title)}. Drag to pan. Control scroll or plus and minus to zoom. Zero to fit. Arrow keys to pan."><div class="diagram-stage">${inline}</div></div><div class="canvas-hint" aria-hidden="true">Drag to pan <span>·</span> Ctrl + scroll to zoom <span>·</span> Click to inspect</div><div class="map-legend" aria-label="Component types"><span data-kind="entry">Event</span><span data-kind="compute">Logic</span><span data-kind="decision">Control</span><span data-kind="store">Storage</span><span data-kind="integration">Integration</span><span data-kind="interface">Interface</span></div></div>
 <aside class="component-inspector" aria-label="Component inspector"><label for="${id}-parts">EXPLORE THE SYSTEM</label><select id="${id}-parts" data-part-select><option value="">Choose a component</option>${parts.map(([key,n])=>`<option value="${key}">${e(n.title)}</option>`).join('')}</select><div class="inspector-content" aria-live="polite" aria-atomic="true"><span class="part-type" data-part-type>OVERVIEW</span><h4 data-part-title>Explore the flow.</h4><div class="part-section"><h5>What it does</h5><p data-part-does>Select a component to see its responsibility, design choices, and limitations.</p></div><div class="part-section" data-why-section hidden><h5>Why this design</h5><p data-part-why></p></div><div class="part-caveat" hidden><h5>Boundary to keep in mind</h5><p data-part-caveat></p></div></div><button type="button" class="focus-component" data-action="focus" disabled>Locate on map ↗</button><div class="component-navigation"><button type="button" data-action="previous" aria-label="Previous component">←</button><span data-part-index>Select a part to begin</span><button type="button" data-action="next" aria-label="Next component">→</button></div></aside></div>
 <details class="map-context"><summary>Scope &amp; reading notes</summary><p>${e(diagram.caption)}</p></details><div class="diagram-actions"><a href="../diagrams/${id}.svg" target="_blank" rel="noreferrer">Open SVG ↗</a><a href="../diagrams/${id}.mmd" download>Download Mermaid ↓</a></div><details><summary>Read the Mermaid definition</summary><pre><code>${e(source)}</code></pre></details><script type="application/json" data-component-notes>${JSON.stringify(notes).replace(/</g,'\\u003c')}</script></figure>`;
}
